GHA Migration
splitio/split-synchronizer pull request #141
Opened 2021-08-31 18:35 UTC by LucianoCaravajal

# Split Synchronizer

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2021-09-01 15:26 UTC, Israphel commented
Remember the "unstable" workflow. That pushes a container to the docker-dev repository, for every branch (non PRs) which aren't master. And the tag is a short hash.

```yaml
  - name: unstable
    if: NOT (type = pull_request) AND NOT (branch = master)

```

```yaml
    - stage: unstable
      language: minimal
      services:
        - docker
      before_script:
        - COMMIT=$(git rev-parse --short HEAD)
      script:
        - docker build -t ${ARTIFACTORY_REGISTRY}/split-synchronizer:${COMMIT} .
      deploy:
        provider: script
        script: >-
          echo "${ARTIFACTORY_PASSWORD}" | docker login -u "${ARTIFACTORY_USER}" --password-stdin "${ARTIFACTORY_REGISTRY}" &&
          docker push ${ARTIFACTORY_REGISTRY}/split-synchronizer
        skip_cleanup: true
        on:
          all_branches: true
```

2021-09-08 17:25 UTC, Israphel requested changes

2021-09-08 17:25 UTC, Israphel commented on .github/workflows/unstable.yml
> +          tags: splitio-docker-dev.jfrog.io/${{ github.event.repository.name }}:$SHORT_SHA
that's not how you reference a gihub actions env var

2021-09-08 21:15 UTC, Israphel requested changes

2021-09-08 21:15 UTC, Israphel commented on .github/workflows/cd.yml
> +  deploy-to-stage:
split-synchronizer is not something we deploy.

2021-09-08 21:15 UTC, Israphel commented on .github/workflows/cd.yml
> +            https://r2d2.split-stage.io/deployment
end of line missing

2021-09-08 21:15 UTC, Israphel commented on .github/workflows/ci.yml
> +            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
end of line missing

2021-09-08 21:15 UTC, Israphel commented on .github/workflows/unstable.yml
> +          tags: splitio-docker-dev.jfrog.io/${{ github.event.repository.name }}:${{ env.SHORT_SHA }}
end of line missing

2021-09-08 21:15 UTC, Israphel commented on .github/workflows/cd.yml
> +      - master
leave a line before jobs

2021-09-08 21:17 UTC, Israphel submitted a review, later dismissed

2021-09-08 21:17 UTC, Israphel commented on .github/workflows/unstable.yml
> +        run: echo "SHORT_SHA=git rev-parse --short HEAD" >> $GITHUB_ENV
`run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV`

2021-09-28 14:18 UTC, mmelograno approved these changes

2021-09-28 15:16 UTC, nikoe14 approved these changes

2021-09-28 15:17 UTC, Israphel approved these changes

2021-09-29 13:24 UTC, merged