Fix dashboard
splitio/split-synchronizer pull request #266
Opened 2024-01-24 19:21 UTC by sanzmauro

# Split Synchronizer

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2024-01-29 13:59 UTC, gthea submitted a review, later dismissed

2024-01-29 17:45 UTC, gthea submitted a review, later dismissed

2024-01-30 15:28 UTC, mmelograno requested changes
Alpine released 3.19.1

2024-01-30 16:47 UTC, mmelograno approved these changes

2024-01-30 17:18 UTC, merged